name : Python CI

# Trigger the workflow on push to the main branch or pull request
on :
    push:
        branches :
            - main
    pull_request:
        branches :
            - main

jobs :
    test:
        runs-on : ubuntu-latest
        steps :
            ## Checkout the repository to the GitHub Actions runner
            - name : Checkout the code
              uses : actions/checkout@v2

            ## Install Python
            - name : Install Python
              uses : actions/setup-python@v2
              with :
                  python-version : 3.8

            ## Install dependencies
            - name : Install dependencies
              run : |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            ## Run tests
            - name : Run tests
              run : pytest
